spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stopcar?characterEncoding=utf-8
    username: root
    password: Root_123
    driver-class-name: com.mysql.jdbc.Driver

  mybatis:
    typeAliasesPackage: com.sqgl.pojo
    mapperLocations: classpath:mappers/*.xml

  mvc:
    view:
      prefix: /templates/
      suffix: .html

server:
  port: 8080
